version: '3.6'
services:
  lfatmug-backend:
    image: docker.fatmug.backend
    container_name: fatmug-backend
    ports:
      - "8000:8000"
    restart: always
    networks:
      - lb_net
        
networks:
  lb_net:
    name: lb_net
    external: true
    

    
