# Generated by Django 4.1.7 on 2024-05-01 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='id',
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_number',
            field=models.CharField(auto_created=True, max_length=200, primary_key=True, serialize=False, unique=True),
        ),
    ]
