# Generated by Django 4.1.7 on 2024-05-02 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_purchaseorder_issue_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
