# Generated by Django 4.1.7 on 2024-05-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_purchaseorder_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='is_product_delivered_on_time',
            field=models.BooleanField(auto_created=True, default=False),
        ),
    ]
