# Generated by Django 4.1.7 on 2024-05-02 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_purchaseorder_is_product_delivered_on_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='is_product_delivered_on_time',
            field=models.BooleanField(),
        ),
    ]
